###
GET http://localhost:4004/odata/v4/booksservice/Books
Content-Type:application/json

###

POST http://localhost:4004/odata/v4/booksservice/Books
Content-Type: application/json

{
  "bookNumber": "BK006",
  "Title": "Book 6",
  "PublishedYear": 2020,
  "Address": "Address 6"
}

###

POST http://localhost:4004/odata/v4/booksservice/countChapters
Content-Type:application/json

{
  "bookId": "2"
}